In [384]:
import pandas as pd

In [385]:
df=pd.read_csv(r"C:\Users\thang\OneDrive\Desktop\Documents\Real time fraud detection\fraud_dataset.csv")
df

,transaction_id,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count,is_fraud
0,TXN100000,902.09,4,Restaurants,Pune,POS Terminal,1,0,0
1,TXN100001,235.10,15,Entertainment,Hyderabad,Desktop,6,0,0
2,TXN100002,1408.74,9,Clothing,Chennai,Mobile,10,1,0
3,TXN100003,1703.71,8,Entertainment,Delhi,Mobile,5,0,0
4,TXN100004,94.53,16,Restaurants,Chennai,Desktop,13,0,1
...,...,...,...,...,...,...,...,...,...
995,TXN100995,946.45,13,Fuel,Coimbatore,Desktop,10,0,0
996,TXN100996,1431.99,19,Fuel,Madurai,Mobile,13,0,0
997,TXN100997,750.83,16,Clothing,Coimbatore,Desktop,8,0,0
998,TXN100998,758.06,3,Grocery,Chennai,Desktop,8,0,0
999,TXN100999,1515.88,1,Healthcare,Pune,Mobile,8,0,0

In [386]:
df.head()

,transaction_id,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count,is_fraud
0,TXN100000,902.09,4,Restaurants,Pune,POS Terminal,1,0,0
1,TXN100001,235.10,15,Entertainment,Hyderabad,Desktop,6,0,0
2,TXN100002,1408.74,9,Clothing,Chennai,Mobile,10,1,0
3,TXN100003,1703.71,8,Entertainment,Delhi,Mobile,5,0,0
4,TXN100004,94.53,16,Restaurants,Chennai,Desktop,13,0,1

In [387]:
df.tail()

,transaction_id,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count,is_fraud
995,TXN100995,946.45,13,Fuel,Coimbatore,Desktop,10,0,0
996,TXN100996,1431.99,19,Fuel,Madurai,Mobile,13,0,0
997,TXN100997,750.83,16,Clothing,Coimbatore,Desktop,8,0,0
998,TXN100998,758.06,3,Grocery,Chennai,Desktop,8,0,0
999,TXN100999,1515.88,1,Healthcare,Pune,Mobile,8,0,0

In [388]:
df.shape

(1000, 9)

In [389]:
df.describe()

,amount,transaction_hour,transaction_frequency,previous_fraud_count,is_fraud
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000
mean,1048.914900,11.487000,8.097000,0.189000,0.10000
std,1311.291947,6.942192,4.284384,0.530623,0.30015
min,50.000000,0.000000,1.000000,0.000000,0.00000
25%,331.517500,5.000000,4.000000,0.000000,0.00000
50%,669.265000,11.000000,8.000000,0.000000,0.00000
75%,1199.770000,18.000000,12.000000,0.000000,0.00000
max,15976.170000,23.000000,15.000000,3.000000,1.00000

In [390]:
df.columns

Index(['transaction_id', 'amount', 'transaction_hour', 'merchant_category',
       'location', 'device_type', 'transaction_frequency',
       'previous_fraud_count', 'is_fraud'],
      dtype='str')

In [391]:
df.dtypes

transaction_id               str
amount                   float64
transaction_hour           int64
merchant_category            str
location                     str
device_type                  str
transaction_frequency      int64
previous_fraud_count       int64
is_fraud                   int64
dtype: object

In [392]:
df.isnull().sum()

transaction_id           0
amount                   0
transaction_hour         0
merchant_category        0
location                 0
device_type              0
transaction_frequency    0
previous_fraud_count     0
is_fraud                 0
dtype: int64

In [393]:
from sklearn.preprocessing import LabelEncoder
Le=LabelEncoder()

In [394]:
df.nunique()

transaction_id           1000
amount                    995
transaction_hour           24
merchant_category          10
location                   10
device_type                 5
transaction_frequency      15
previous_fraud_count        4
is_fraud                    2
dtype: int64

In [395]:
df.drop(["transaction_id"],axis=1,inplace=True)

In [396]:
obj=df.select_dtypes(include=['object','str']).columns
obj

Index(['merchant_category', 'location', 'device_type'], dtype='str')

In [397]:
for i in obj:
    df[i]=Le.fit_transform(df[i].astype(str))   
df

,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count,is_fraud
0,902.09,4,8,8,3,1,0,0
1,235.10,15,2,4,1,6,0,0
2,1408.74,9,0,1,2,10,1,0
3,1703.71,8,2,3,2,5,0,0
4,94.53,16,8,1,1,13,0,1
...,...,...,...,...,...,...,...,...
995,946.45,13,3,2,1,10,0,0
996,1431.99,19,3,6,2,13,0,0
997,750.83,16,0,2,1,8,0,0
998,758.06,3,4,1,1,8,0,0
999,1515.88,1,5,8,2,8,0,0

In [398]:
df.dtypes

amount                   float64
transaction_hour           int64
merchant_category          int64
location                   int64
device_type                int64
transaction_frequency      int64
previous_fraud_count       int64
is_fraud                   int64
dtype: object

In [399]:
df.head()

,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count,is_fraud
0,902.09,4,8,8,3,1,0,0
1,235.10,15,2,4,1,6,0,0
2,1408.74,9,0,1,2,10,1,0
3,1703.71,8,2,3,2,5,0,0
4,94.53,16,8,1,1,13,0,1

In [400]:
from sklearn.preprocessing import MinMaxScaler
minmax=MinMaxScaler(feature_range=(0,1))

In [401]:
X=df.drop(['is_fraud'], axis=1)
X

,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count
0,902.09,4,8,8,3,1,0
1,235.10,15,2,4,1,6,0
2,1408.74,9,0,1,2,10,1
3,1703.71,8,2,3,2,5,0
4,94.53,16,8,1,1,13,0
...,...,...,...,...,...,...,...
995,946.45,13,3,2,1,10,0
996,1431.99,19,3,6,2,13,0
997,750.83,16,0,2,1,8,0
998,758.06,3,4,1,1,8,0
999,1515.88,1,5,8,2,8,0

In [402]:
Y=df['is_fraud']
Y

0      0
1      0
2      0
3      0
4      1
      ..
995    0
996    0
997    0
998    0
999    0
Name: is_fraud, Length: 1000, dtype: int64

In [403]:
X1=minmax.fit_transform(X)
X1

array([[0.05350251, 0.17391304, 0.88888889, ..., 0.75      , 0.        ,
        0.        ],
       [0.01162238, 0.65217391, 0.22222222, ..., 0.25      , 0.35714286,
        0.        ],
       [0.08531493, 0.39130435, 0.        , ..., 0.5       , 0.64285714,
        0.33333333],
       ...,
       [0.04400493, 0.69565217, 0.        , ..., 0.25      , 0.5       ,
        0.        ],
       [0.0444589 , 0.13043478, 0.44444444, ..., 0.25      , 0.5       ,
        0.        ],
       [0.09204222, 0.04347826, 0.55555556, ..., 0.5       , 0.5       ,
        0.        ]], shape=(1000, 7))

In [404]:
X1=pd.DataFrame(X1, columns=X.columns)
X1

,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count
0,0.053503,0.173913,0.888889,0.888889,0.75,0.000000,0.000000
1,0.011622,0.652174,0.222222,0.444444,0.25,0.357143,0.000000
2,0.085315,0.391304,0.000000,0.111111,0.50,0.642857,0.333333
3,0.103836,0.347826,0.222222,0.333333,0.50,0.285714,0.000000
4,0.002796,0.695652,0.888889,0.111111,0.25,0.857143,0.000000
...,...,...,...,...,...,...,...
995,0.056288,0.565217,0.333333,0.222222,0.25,0.642857,0.000000
996,0.086775,0.826087,0.333333,0.666667,0.50,0.857143,0.000000
997,0.044005,0.695652,0.000000,0.222222,0.25,0.500000,0.000000
998,0.044459,0.130435,0.444444,0.111111,0.25,0.500000,0.000000
999,0.092042,0.043478,0.555556,0.888889,0.50,0.500000,0.000000

In [405]:
X1.describe

<bound method NDFrame.describe of        amount  transaction_hour  merchant_category  location  device_type  \
0    0.053503          0.173913           0.888889  0.888889         0.75
1    0.011622          0.652174           0.222222  0.444444         0.25
2    0.085315          0.391304           0.000000  0.111111         0.50
3    0.103836          0.347826           0.222222  0.333333         0.50
4    0.002796          0.695652           0.888889  0.111111         0.25
..        ...               ...                ...       ...          ...
995  0.056288          0.565217           0.333333  0.222222         0.25
996  0.086775          0.826087           0.333333  0.666667         0.50
997  0.044005          0.695652           0.000000  0.222222         0.25
998  0.044459          0.130435           0.444444  0.111111         0.25
999  0.092042          0.043478           0.555556  0.888889         0.50

     transaction_frequency  previous_fraud_count
0                 0.000000              0.000000
1                 0.357143              0.000000
2                 0.642857              0.333333
3                 0.285714              0.000000
4                 0.857143              0.000000
..                     ...                   ...
995               0.642857              0.000000
996               0.857143              0.000000
997               0.500000              0.000000
998               0.500000              0.000000
999               0.500000              0.000000

[1000 rows x 7 columns]>

In [406]:
X2=pd.concat([X1,Y], axis=1)
X2

,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count,is_fraud
0,0.053503,0.173913,0.888889,0.888889,0.75,0.000000,0.000000,0
1,0.011622,0.652174,0.222222,0.444444,0.25,0.357143,0.000000,0
2,0.085315,0.391304,0.000000,0.111111,0.50,0.642857,0.333333,0
3,0.103836,0.347826,0.222222,0.333333,0.50,0.285714,0.000000,0
4,0.002796,0.695652,0.888889,0.111111,0.25,0.857143,0.000000,1
...,...,...,...,...,...,...,...,...
995,0.056288,0.565217,0.333333,0.222222,0.25,0.642857,0.000000,0
996,0.086775,0.826087,0.333333,0.666667,0.50,0.857143,0.000000,0
997,0.044005,0.695652,0.000000,0.222222,0.25,0.500000,0.000000,0
998,0.044459,0.130435,0.444444,0.111111,0.25,0.500000,0.000000,0
999,0.092042,0.043478,0.555556,0.888889,0.50,0.500000,0.000000,0

In [407]:
X2.to_csv("Real_time_fraud_detection.csv")

LOGISTIC REGRESSION

In [408]:
X2.to_csv(r"Real_time_fraud_detection.csv")
X2

,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count,is_fraud
0,0.053503,0.173913,0.888889,0.888889,0.75,0.000000,0.000000,0
1,0.011622,0.652174,0.222222,0.444444,0.25,0.357143,0.000000,0
2,0.085315,0.391304,0.000000,0.111111,0.50,0.642857,0.333333,0
3,0.103836,0.347826,0.222222,0.333333,0.50,0.285714,0.000000,0
4,0.002796,0.695652,0.888889,0.111111,0.25,0.857143,0.000000,1
...,...,...,...,...,...,...,...,...
995,0.056288,0.565217,0.333333,0.222222,0.25,0.642857,0.000000,0
996,0.086775,0.826087,0.333333,0.666667,0.50,0.857143,0.000000,0
997,0.044005,0.695652,0.000000,0.222222,0.25,0.500000,0.000000,0
998,0.044459,0.130435,0.444444,0.111111,0.25,0.500000,0.000000,0
999,0.092042,0.043478,0.555556,0.888889,0.50,0.500000,0.000000,0

In [409]:
A=df.drop(['is_fraud'], axis=1)
A

,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count
0,902.09,4,8,8,3,1,0
1,235.10,15,2,4,1,6,0
2,1408.74,9,0,1,2,10,1
3,1703.71,8,2,3,2,5,0
4,94.53,16,8,1,1,13,0
...,...,...,...,...,...,...,...
995,946.45,13,3,2,1,10,0
996,1431.99,19,3,6,2,13,0
997,750.83,16,0,2,1,8,0
998,758.06,3,4,1,1,8,0
999,1515.88,1,5,8,2,8,0

In [410]:
B=df['is_fraud']
B

0      0
1      0
2      0
3      0
4      1
      ..
995    0
996    0
997    0
998    0
999    0
Name: is_fraud, Length: 1000, dtype: int64

In [411]:
from sklearn.model_selection import train_test_split
A_train,A_test,B_train,B_test=train_test_split(A,B,test_size=0.25,random_state=42)

In [412]:
from sklearn.linear_model import LogisticRegression
logreg=LogisticRegression(max_iter=300)

In [413]:
model=logreg.fit(A_train, B_train)

In [414]:
B_pred=model.predict(A_test)
B_pred

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [415]:
from sklearn.metrics import confusion_matrix,precision_score,recall_score,f1_score,accuracy_score, classification_report

In [416]:
print(confusion_matrix(B_test,B_pred))

[[221   3]
 [ 16  10]]

In [417]:
print(precision_score(B_test, B_pred))

0.7692307692307693

In [418]:
print(accuracy_score(B_test,B_pred))

0.924

In [419]:
print(recall_score(B_test,B_pred))

0.38461538461538464

In [420]:
print(f1_score(B_test,B_pred))

0.5128205128205128

In [421]:
print(classification_report(B_test,B_pred))

              precision    recall  f1-score   support

           0       0.93      0.99      0.96       224
           1       0.77      0.38      0.51        26

    accuracy                           0.92       250
   macro avg       0.85      0.69      0.74       250
weighted avg       0.92      0.92      0.91       250

In [422]:
A_train.head(10)

,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count
82,462.64,20,3,2,4,7,0
991,2919.81,7,7,3,4,12,0
789,571.89,10,1,7,3,1,0
894,486.99,17,2,3,3,14,0
398,1130.10,0,2,4,2,11,0
323,1409.33,5,1,5,4,2,0
519,3391.19,8,9,5,2,13,0
916,2797.00,17,0,8,0,12,0
922,749.36,4,4,5,3,15,0
5,180.88,9,6,6,2,13,0

In [423]:
B_train.head(10)

82     0
991    0
789    0
894    0
398    0
323    0
519    1
916    0
922    0
5      0
Name: is_fraud, dtype: int64

In [424]:
model.predict([[462.64,	20,	3,	2,	4,	7,	0]])

C:\Users\thang\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

RANDOM FOREST

In [425]:
X2.to_csv(r"Real_time_fraud_detection.csv")
X2

,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count,is_fraud
0,0.053503,0.173913,0.888889,0.888889,0.75,0.000000,0.000000,0
1,0.011622,0.652174,0.222222,0.444444,0.25,0.357143,0.000000,0
2,0.085315,0.391304,0.000000,0.111111,0.50,0.642857,0.333333,0
3,0.103836,0.347826,0.222222,0.333333,0.50,0.285714,0.000000,0
4,0.002796,0.695652,0.888889,0.111111,0.25,0.857143,0.000000,1
...,...,...,...,...,...,...,...,...
995,0.056288,0.565217,0.333333,0.222222,0.25,0.642857,0.000000,0
996,0.086775,0.826087,0.333333,0.666667,0.50,0.857143,0.000000,0
997,0.044005,0.695652,0.000000,0.222222,0.25,0.500000,0.000000,0
998,0.044459,0.130435,0.444444,0.111111,0.25,0.500000,0.000000,0
999,0.092042,0.043478,0.555556,0.888889,0.50,0.500000,0.000000,0

In [426]:
P=df.drop(['is_fraud'],axis=1)
P

,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count
0,902.09,4,8,8,3,1,0
1,235.10,15,2,4,1,6,0
2,1408.74,9,0,1,2,10,1
3,1703.71,8,2,3,2,5,0
4,94.53,16,8,1,1,13,0
...,...,...,...,...,...,...,...
995,946.45,13,3,2,1,10,0
996,1431.99,19,3,6,2,13,0
997,750.83,16,0,2,1,8,0
998,758.06,3,4,1,1,8,0
999,1515.88,1,5,8,2,8,0

In [427]:
Q=df['is_fraud']
Q

0      0
1      0
2      0
3      0
4      1
      ..
995    0
996    0
997    0
998    0
999    0
Name: is_fraud, Length: 1000, dtype: int64

In [428]:
from sklearn.model_selection import train_test_split
P_train,P_test,Q_train,Q_test = train_test_split(P,Q,test_size=0.25,random_state=42)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report,f1_score,precision_score,recall_score

rf_clf = RandomForestClassifier(random_state=42)
rf_clf.fit(P_train, Q_train)

Q_pred_rf = rf_clf.predict(P_test)

print(accuracy_score(Q_test, Q_pred_rf))
print(confusion_matrix(Q_test, Q_pred_rf))
print(classification_report(Q_test, Q_pred_rf))
print(f1_score(Q_test, Q_pred_rf))
print(precision_score(Q_test, Q_pred_rf))
print(recall_score(Q_test, Q_pred_rf))

0.94
[[222   2]
 [ 13  13]]
              precision    recall  f1-score   support

           0       0.94      0.99      0.97       224
           1       0.87      0.50      0.63        26

    accuracy                           0.94       250
   macro avg       0.91      0.75      0.80       250
weighted avg       0.94      0.94      0.93       250

In [430]:
P_train.head()

,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count
82,462.64,20,3,2,4,7,0
991,2919.81,7,7,3,4,12,0
789,571.89,10,1,7,3,1,0
894,486.99,17,2,3,3,14,0
398,1130.10,0,2,4,2,11,0

In [431]:
Q_train.head()

82     0
991    0
789    0
894    0
398    0
Name: is_fraud, dtype: int64

In [432]:
model.predict([[462.64,	20,	3,	2,	4,	7,	0]])

C:\Users\thang\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

XG-BOOST

In [433]:
X2.to_csv(r"Real_time_fraud_detection.csv")
X2

,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count,is_fraud
0,0.053503,0.173913,0.888889,0.888889,0.75,0.000000,0.000000,0
1,0.011622,0.652174,0.222222,0.444444,0.25,0.357143,0.000000,0
2,0.085315,0.391304,0.000000,0.111111,0.50,0.642857,0.333333,0
3,0.103836,0.347826,0.222222,0.333333,0.50,0.285714,0.000000,0
4,0.002796,0.695652,0.888889,0.111111,0.25,0.857143,0.000000,1
...,...,...,...,...,...,...,...,...
995,0.056288,0.565217,0.333333,0.222222,0.25,0.642857,0.000000,0
996,0.086775,0.826087,0.333333,0.666667,0.50,0.857143,0.000000,0
997,0.044005,0.695652,0.000000,0.222222,0.25,0.500000,0.000000,0
998,0.044459,0.130435,0.444444,0.111111,0.25,0.500000,0.000000,0
999,0.092042,0.043478,0.555556,0.888889,0.50,0.500000,0.000000,0

In [434]:
M=df.drop(['is_fraud'], axis=1)
M

,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count
0,902.09,4,8,8,3,1,0
1,235.10,15,2,4,1,6,0
2,1408.74,9,0,1,2,10,1
3,1703.71,8,2,3,2,5,0
4,94.53,16,8,1,1,13,0
...,...,...,...,...,...,...,...
995,946.45,13,3,2,1,10,0
996,1431.99,19,3,6,2,13,0
997,750.83,16,0,2,1,8,0
998,758.06,3,4,1,1,8,0
999,1515.88,1,5,8,2,8,0

In [435]:
N=df['is_fraud']
N

0      0
1      0
2      0
3      0
4      1
      ..
995    0
996    0
997    0
998    0
999    0
Name: is_fraud, Length: 1000, dtype: int64

In [436]:
from sklearn.model_selection import train_test_split
M_train,M_test,N_train,N_test=train_test_split(M,N,test_size=0.25,random_state=42)

In [437]:
from xgboost import XGBClassifier
model_xgb = XGBClassifier()
model_xgb.fit(M_train,N_train)
pred_xgb = model_xgb.predict(M_test)
pred_xgb

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix,precision_score,recall_score,f1_score,accuracy_score, classification_report

In [444]:
print(accuracy_score(B_test,pred_xgb))
print(confusion_matrix(B_test,pred_xgb))
print(classification_report(B_test,pred_xgb))
print(f1_score(B_test, pred_xgb))
print(precision_score(B_test, pred_xgb))
print(recall_score(B_test, pred_xgb))

0.952
[[221   3]
 [  9  17]]
              precision    recall  f1-score   support

           0       0.96      0.99      0.97       224
           1       0.85      0.65      0.74        26

    accuracy                           0.95       250
   macro avg       0.91      0.82      0.86       250
weighted avg       0.95      0.95      0.95       250

0.7391304347826086
0.85
0.6538461538461539

In [440]:
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 24)

In [441]:
M_train.head()

,amount,transaction_hour,merchant_category,location,device_type,transaction_frequency,previous_fraud_count
82,462.64,20,3,2,4,7,0
991,2919.81,7,7,3,4,12,0
789,571.89,10,1,7,3,1,0
894,486.99,17,2,3,3,14,0
398,1130.10,0,2,4,2,11,0

In [442]:
N_train.head()

82     0
991    0
789    0
894    0
398    0
Name: is_fraud, dtype: int64

In [443]:
model.predict([[462.64,	2,	3,	2,	4,	7,	0]])

C:\Users\thang\AppData\Roaming\Python\Python314\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [451]:
import pandas as pd
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

# 1. Load data and define X and y
df = pd.read_csv("fraud_dataset.csv")   # use your actual file name/path
X = df.drop(columns=["is_fraud", "transaction_id"])
y = df["is_fraud"]

# 2. Column groups
cat_cols = ["merchant_category", "location", "device_type"]
num_cols = ["amount", "transaction_hour", "transaction_frequency", "previous_fraud_count"]

def make_preprocessor(scale=False):
    return ColumnTransformer([
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
        ("num", StandardScaler() if scale else "passthrough", num_cols),
    ])

neg, pos = (y == 0).sum(), (y == 1).sum()

# 3. The three pipelines
lr_pipeline = Pipeline([
    ("prep", make_preprocessor(scale=True)),
    ("model", LogisticRegression(class_weight="balanced", max_iter=1000)),
])

rf_pipeline = Pipeline([
    ("prep", make_preprocessor()),
    ("model", RandomForestClassifier(n_estimators=300, class_weight="balanced", random_state=42)),
])

xgb_pipeline = Pipeline([
    ("prep", make_preprocessor()),
    ("model", XGBClassifier(scale_pos_weight=neg / pos, eval_metric="logloss", random_state=42)),
])

In [452]:
import pandas as pd
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.metrics import roc_auc_score, average_precision_score, precision_score, recall_score, f1_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
models = {"LogReg": lr_pipeline, "RandomForest": rf_pipeline, "XGBoost": xgb_pipeline}

rows = []
for name, m in models.items():
    proba = cross_val_predict(m, X, y, cv=cv, method="predict_proba")[:, 1]
    pred = (proba >= 0.5).astype(int)
    rows.append({
        "model": name,
        "ROC-AUC": roc_auc_score(y, proba),
        "PR-AUC": average_precision_score(y, proba),
        "precision": precision_score(y, pred),
        "recall": recall_score(y, pred),
        "F1": f1_score(y, pred),
    })

print(pd.DataFrame(rows).round(3))

          model  ROC-AUC  PR-AUC  precision  recall     F1
0        LogReg    0.887   0.639      0.370    0.77  0.500
1  RandomForest    0.913   0.683      0.893    0.25  0.391
2       XGBoost    0.904   0.695      0.635    0.66  0.647

In [453]:
import numpy as np
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import precision_score, recall_score, f1_score

proba_xgb = cross_val_predict(xgb_pipeline, X, y, cv=cv, method="predict_proba")[:, 1]

rows = []
for t in np.arange(0.10, 0.95, 0.05):
    pred = (proba_xgb >= t).astype(int)
    rows.append({
        "threshold": round(t, 2),
        "precision": precision_score(y, pred, zero_division=0),
        "recall": recall_score(y, pred),
        "F1": f1_score(y, pred),
    })

print(pd.DataFrame(rows).round(3))

    threshold  precision  recall     F1
0        0.10      0.494    0.77  0.602
1        0.15      0.507    0.71  0.592
2        0.20      0.526    0.71  0.604
3        0.25      0.552    0.69  0.613
4        0.30      0.570    0.69  0.624
5        0.35      0.576    0.68  0.624
6        0.40      0.618    0.68  0.648
7        0.45      0.620    0.67  0.644
8        0.50      0.635    0.66  0.647
9        0.55      0.660    0.62  0.639
10       0.60      0.670    0.61  0.639
11       0.65      0.686    0.59  0.634
12       0.70      0.712    0.57  0.633
13       0.75      0.730    0.54  0.621
14       0.80      0.771    0.54  0.635
15       0.85      0.791    0.53  0.635
16       0.90      0.812    0.52  0.634

In [454]:
scores = pd.Series(proba_xgb, index=y.index)
zone = pd.cut(scores, bins=[0, 0.30, 0.80, 1.0],
              labels=["ALLOW", "ALERT", "BLOCK"], right=False, include_lowest=True)

summary = pd.DataFrame({"zone": zone, "is_fraud": y}).groupby("zone").agg(
    transactions=("is_fraud", "size"),
    frauds=("is_fraud", "sum"),
    fraud_rate=("is_fraud", "mean"),
)
print(summary.round(3))

       transactions  frauds  fraud_rate
zone
ALLOW           879      31       0.035
ALERT            51      15       0.294
BLOCK            70      54       0.771

In [456]:
import os
print(os.getcwd())                 # where the notebook is running
print(os.path.isfile("models"))    # True means it's a file
print(os.path.isdir("models"))     # should be False

c:\Users\thang\OneDrive\Desktop\Documents\Real time fraud detection
True
False

In [458]:
import joblib, json, os

os.makedirs("saved_models", exist_ok=True)
xgb_pipeline.fit(X, y)
joblib.dump(xgb_pipeline, "saved_models/fraud_model.joblib")

with open("config.json", "w") as f:
    json.dump({"allow_below": 0.30, "block_at_or_above": 0.80}, f, indent=2)

print("Saved in:", os.getcwd())
print(os.listdir("saved_models"))

Saved in: c:\Users\thang\OneDrive\Desktop\Documents\Real time fraud detection
['fraud_model.joblib']

In [459]:
import json, joblib

print(json.load(open("config.json")))
model = joblib.load("saved_models/fraud_model.joblib")
print("Risk score:", round(float(model.predict_proba(X.iloc[[0]])[:, 1][0]), 3))

{'allow_below': 0.3, 'block_at_or_above': 0.8}
Risk score: 0.01